version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: bigsmoke-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bigsmoke
      MYSQL_USER: bigsmoke
      MYSQL_PASSWORD: bigsmoke123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - bigsmoke-network
    command: --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: bigsmoke-phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - bigsmoke-network

volumes:
  mysql_data:

networks:
  bigsmoke-network:
    driver: bridge
